-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
        FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, A.PARENT_ID, GEN.GENERATION + 1 AS G
        FROM ECOLI_DATA AS A
    JOIN GEN ON GEN.ID = A.PARENT_ID
)

SELECT ID FROM GEN WHERE GENERATION = 3 ORDER BY ID