-- 코드를 입력하세요
SELECT * FROM REST_INFO WHERE FOOD_TYPE='일식';
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES FROM REST_INFO AS RI JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS G ON G.FOOD_TYPE=RI.FOOD_TYPE WHERE RI.FAVORITES=G.FAVORITES ORDER BY FOOD_TYPE DESC;