-- 코드를 작성해주세요
SELECT 
    SUB.ID AS ID, 
    CASE 
        WHEN SUB.N = 1 THEN 'CRITICAL'
        WHEN SUB.N = 2 THEN 'HIGH'
        WHEN SUB.N = 3 THEN 'MEDIUM'
        WHEN SUB.N = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM (SELECT *, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS N
    FROM ECOLI_DATA) AS SUB
ORDER BY SUB.ID
