# -- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS G
        FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, A.PARENT_ID, GEN.G + 1 AS GENERATION
        FROM ECOLI_DATA A
    JOIN GEN ON GEN.ID = A.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GEN.G AS GENERATION FROM ECOLI_DATA E
    JOIN GEN ON GEN.ID = E.ID
    LEFT JOIN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA) AS SUB ON SUB.PARENT_ID = E.ID
    WHERE SUB.PARENT_ID IS NULL
    GROUP BY GEN.G