-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF AS FH JOIN ICECREAM_INFO AS II ON FH.FLAVOR=II.FLAVOR GROUP BY II.INGREDIENT_TYPE ORDER BY TOTAL_ORDER ASC;
# SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(FIRST_HALF.TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF AS FH JOIN ICECREAM_INFO AS II ON FH.FLAVOR=II.FLAVOR;
# GROUP BY FH.FLAVOR ORDER BY TOTAL_ORDER;