-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR WHERE 
    CASE 
        WHEN OPTIONS LIKE '%열선시트%' THEN TRUE
        WHEN OPTIONS LIKE '%통풍시트%' THEN TRUE
        WHEN OPTIONS LIKE '%가죽시트%' THEN TRUE
        ELSE FALSE
    END
    GROUP BY CAR_TYPE ORDER BY CAR_TYPE;